config/install/moderation_dashboard.settings.yml, config/install/views.view.content_search.yml
**Details**
- Enable ChartJS CDN by defualt.
- Remove content search views cache settings.
=> convivial-28333: Improve installer profile

README.md, assets/.github/scripts/build.sh, composer.json
Mirrored from morpht/convivial-demo 32645-hotfix2 @ bbd6946.
=> convivial-32645: Fixing Drupal scafolding step

composer.json
```
+--------------------------------------+-------+--------+--------------------------------------------------------------------------------+
| Production Changes                   | From  | To     | Compare                                                                        |
+--------------------------------------+-------+--------+--------------------------------------------------------------------------------+
| pantheon-systems/drupal-integrations | 9.0.5 | 10.0.1 | https://github.com/pantheon-systems/drupal-integrations/compare/9.0.5...10.0.1 |
+--------------------------------------+-------+--------+--------------------------------------------------------------------------------+
```
Mirrored from morpht/convivial-demo 29725 @ f142060.
=> convivial-29725: Update pantheon-systems/drupal-integrations package.

config/install/block.block.overridepersonalisation.yml, config/install/block.block.views_block__content_information_summary.yml, config/install/convivial_bootstrap.settings.yml, config/install/views.view.content_information.yml
Mirrored from morpht/convivial-demo 32255 @ d6ce70a.
=> convivial-32255: Added Node info block and convivial-32256: Personalisation override.

composer.json
```
+--------------------+---------+---------+---------------------------------------------------------+
| Production Changes | From    | To      | Compare                                                 |
+--------------------+---------+---------+---------------------------------------------------------+
| morpht/mdt         | ec72d8b | ee8776f | https://github.com/morpht/mdt/compare/ec72d8b...ee8776f |
+--------------------+---------+---------+---------------------------------------------------------+
```
Mirrored from morpht/convivial-demo convivial-32673 @ 48e5817.
=> convivial-32673: Updated mdt package.

composer.json
Mirrored from morpht/convivial-demo convivial-32821 @ 431d90b.
=> convivial-32821: Clean up to the composer json file.

config/install/convivial_profiler.settings.yml, config/install/core.entity_form_display.taxonomy_term.intent.default.yml, config/install/custom_meta.settings.yml, config/install/field.field.taxonomy_term.intent.field_key.yml, config/install/metatag.metatag_defaults.node__article.yml, config/install/metatag.metatag_defaults.taxonomy_term__intent.yml
Mirrored from morpht/convivial-demo@fb3a581 (33094).
=> convivial-33094: [Convivial Profiler] Add unstore process plugin.

config/install/convivial_profiler.settings.yml
Mirrored from morpht/convivial-demo@ab2285d (33456).
=> convivial-33456: Fixed Stage Override profiler.

composer.json, config/install/convivial_content.settings.yml, convivial.info.yml
Mirrored from morpht/convivial-demo@37d4426 (32855).
=> convivial-32855: Added Convivial Content module.

convivial.profile
Mirrored from morpht/convivial-demo@b654fbb (33981).
=> convivial-33981: Import content while installing Convivial Site.

themes/custom/convivial_bootstrap/convivial_bootstrap.theme
Mirrored from morpht/convivial-demo@a5f2b7c (34140-bug).
=> convivial-34140: Make code more defensive.

composer.json
Mirrored from morpht/convivial-demo@9102e1c (34190).
=> convivial-34190: Deprecated function mb_strtolower().

composer.json
Mirrored from morpht/convivial-demo@d6b02ba (convivial-demo-34308-tty).
=> convivial-demo-34308: Update morpht/mdt.

composer.json
```
+--------------------------------+--------------+---------+
| Production Changes             | From         | To      |
+--------------------------------+--------------+---------+
| bower-asset/popper.js          | v2.11.7      | v2.11.8 |
| drupal/clamav                  | 2.0.1        | 2.0.2   |
| drupal/convivial_core          | 1.0.0        | 1.0.1   |
| drupal/core-composer-scaffold  | 10.1.2       | 10.1.3  |
| drupal/environment_indicator   | 4.0.14       | 4.0.15  |
| drupal/field_formatter_pattern | 1.0.0        | 1.0.1   |
| drupal/geofield                | 1.54.0       | 1.55.0  |
| drupal/geofield_map            | 3.0.11       | 3.0.12  |
| drupal/moderation_dashboard    | 2.1.3        | 2.1.5   |
| drupal/modifiers_pack          | 2.1.0-alpha2 | 2.1.0   |
| …
```
=> convivial-34331: Site updates 202309

themes/custom/convivial_bootstrap/convivial_bootstrap.theme
Mirrored from morpht/convivial-demo@e6877c0 (34235-view-modes-fix).
=> convivial-demo-34235: Fix card and calendar view modes.

themes/custom/convivial_bootstrap/convivial_bootstrap.theme
Mirrored from morpht/convivial-demo@e4b54f3 (34235-view-modes-fix-2).
=> convivial-demo-34235: Make code more defensive.

.github/workflows/build.yml, .github/workflows/nightly.yml, README.md, composer.json
Mirrored from morpht/convivial-demo@ccef1fe (convivial-34436).
=> convivial-34436: Add build and nightly tests to morpht/convivial.

config/install/block.block.convivial_bootstrap_footer.yml
Mirrored from morpht/convivial-demo@74ea2d80 (34462).
=> convivial-34462: Place the footer menu block in the Footer Content region.

config/install/convivial_profiler.settings.yml, config/install/views.view.data_tasks.yml
Mirrored from morpht/convivial-demo@06f2e503 (34651).
=> convivial-demo-34651: Update Default Audience value to audience-general.

convivial.info.yml
Mirrored from morpht/convivial-demo@7c3a592d (34650).
=> convivial-34650: Add distribution key to Convivial Profile info file.

composer.json, config/install/search_api.index.content.yml
```
+---------------------------------+---------+---------+
| Production Changes              | From    | To      |
+---------------------------------+---------+---------+
| doctrine/deprecations           | 1.1.2   | 1.1.3   |
| doctrine/lexer                  | 2.1.0   | 2.1.1   |
| drupal/core                     | 10.2.2  | 10.2.3  |
| drupal/core-composer-scaffold   | 10.2.2  | 10.2.3  |
| drupal/core-project-message     | 10.2.2  | 10.2.3  |
| drupal/core-recommended         | 10.2.2  | 10.2.3  |
| symfony/console                 | v6.4.2  | v6.4.3  |
| symfony/dependency-injection    | v6.4.2  | v6.4.3  |
| symfony/error-handler           | v6.4.0  | v6.4.3  |
| symfony/event-dispatcher        | v6.4.2  | v6.4.3  |
| symfony/filesystem              | v6.4.0  | v6.4.3  |
| …
```
=> convivial-demo-36197: Update Drupal core to latest 10.2.3.

composer.json, config/install/editor.editor.webform_default.yml
```
+---------------------------------+--------+--------+
| Production Changes              | From   | To     |
+---------------------------------+--------+--------+
| drupal/core                     | 10.2.5 | 10.2.6 |
| drupal/core-composer-scaffold   | 10.2.5 | 10.2.6 |
| drupal/core-project-message     | 10.2.5 | 10.2.6 |
| drupal/core-recommended         | 10.2.5 | 10.2.6 |
| drupal/csp                      | 1.30.0 | 1.31.0 |
| drupal/menu_block               | 1.10.0 | 1.11.0 |
| drupal/module_filter            | 4.1.1  | 5.0.0  |
| drush/drush                     | 12.5.1 | 12.5.2 |
| grasmash/yaml-cli               | 3.2.0  | 3.2.1  |
| symfony/console                 | v6.4.6 | v6.4.7 |
| symfony/dependency-injection    | v6.4.6 | v6.4.7 |
| symfony/error-handler           | …
```
=> convivial-demo-37012: Site Updates

composer.json, config/install/block.block.convivial_bootstrap_footer.yml
```
+----------------------------------+--------------+--------------+
| Production Changes               | From         | To           |
+----------------------------------+--------------+--------------+
| chi-teck/drupal-code-generator   | 3.5.0        | 3.6.0        |
| drupal/chosen                    | 4.0.0        | 4.0.1        |
| drupal/chosen_lib                | 4.0.0        | 4.0.1        |
| drupal/config_profile            | a4c086e      | 2.0.0-beta1  |
| drupal/convivial_enricher        | 1.0.0-alpha7 | 1.0.0-alpha8 |
| drupal/focal_point               | 2.0.3        | 2.1.0        |
| drupal/linkit                    | 6.1.3        | 6.1.4        |
| drupal/mailchimp                 | 2.2.2        | 2.2.3        |
| paragonie/constant_time_encoding | v2.6.3       | v2.7.0 …
```
=> convivial-demo-35945: Convivial updates 202405

.github/workflows/build.yml, composer.json
```
+---------------------------------+--------+--------+
| Production Changes              | From   | To     |
+---------------------------------+--------+--------+
| doctrine/event-manager          | 2.0.0  | 2.0.1  |
| drupal/diff                     | 1.3.0  | 1.4.0  |
| drupal/environment_indicator    | 4.0.17 | 4.0.18 |
| drupal/jquery_ui                | 1.6.0  | 1.7.0  |
| drupal/jquery_ui_autocomplete   | 2.0.0  | 2.1.0  |
| drupal/jquery_ui_datepicker     | 2.0.0  | 2.1.0  |
| drupal/jquery_ui_menu           | 2.0.0  | 2.1.0  |
| drupal/jquery_ui_slider         | 2.0.0  | 2.1.0  |
| drupal/key                      | 1.17.0 | 1.18.0 |
| drupal/leaflet_more_maps        | 2.1.3  | 2.2.0  |
| drupal/maxlength                | 2.1.2  | 3.0.0  |
| league/csv                      | …
```
=> convivial-demo-37505: Site Updates + Item List Component modal is not scrollable

composer.json, convivial.info.yml, modules/custom/convivial_breakpoints/convivial_breakpoints.info.yml, modules/custom/convivial_layouts/convivial_layouts.info.yml, modules/custom/convivial_theme_default_render/convivial_theme_default_render.info.yml, themes/custom/convivial_bootstrap/components/accordion-group/accordion-group.component.yml, themes/custom/convivial_bootstrap/components/accordion/accordion.component.yml, themes/custom/convivial_bootstrap/components/animation/animation.component.yml, themes/custom/convivial_bootstrap/components/charts/charts.component.yml, themes/custom/convivial_bootstrap/components/content-tab/content-tab.component.yml, themes/custom/convivial_bootstrap/components/content-tabs/content-tabs.component.yml, themes/custom/convivial_bootstrap/components/fastfacts/fastfacts.component.yml, themes/custom/convivial_bootstrap/components/gallery/gallery.component.yml, themes/custom/convivial_bootstrap/components/geochart/geochart.component.yml, themes/custom/convivial_bootstrap/components/hero-banner/hero-banner.component.yml, themes/custom/convivial_bootstrap/components/lightbox/lightbox.component.yml, themes/custom/convivial_bootstrap/components/map/map.component.yml, themes/custom/convivial_bootstrap/components/social-share/social-share.component.yml, themes/custom/convivial_bootstrap/components/tiles/tiles.component.yml, themes/custom/convivial_bootstrap/components/timeline/timeline.component.yml, themes/custom/convivial_bootstrap/convivial_bootstrap.info.yml, themes/custom/convivial_claro/convivial_claro.info.yml
```
+-------------------------------+--------------+---------+
| Production Changes            | From         | To      |
+-------------------------------+--------------+---------+
| drupal/bpmn_io                | 1.1.4        | 2.0.1   |
| drupal/core                   | 10.3.4       | 10.3.5  |
| drupal/core-composer-scaffold | 10.3.4       | 10.3.5  |
| drupal/core-project-message   | 10.3.4       | 10.3.5  |
| drupal/core-recommended       | 10.3.4       | 10.3.5  |
| drupal/eca                    | 1.1.9        | 2.0.5   |
| drupal/eca_modeller_bpmn      | 1.1.9        | 2.0.5   |
| drupal/eca_ui                 | 2.0.4        | 2.0.5   |
| drupal/eca_vbo                | 1.1.1        | 2.1.1   |
| drupal/migrate_file           | 2.1.2        | REMOVED |
| drupal/profile_switcher …
```
=> convivial-demo-35949: Convivial updates 202409

config/install/gin.settings.yml
```
+------------------------------------+---------------+---------------+
| Production Changes                 | From          | To            |
+------------------------------------+---------------+---------------+
| doctrine/collections               | 2.2.2         | 2.3.0         |
| drupal/convivial_profiler          | 1.0.0-alpha12 | 1.0.0-alpha13 |
| drupal/core                        | 10.4.4        | 10.4.5        |
| drupal/core-composer-scaffold      | 10.4.4        | 10.4.5        |
| drupal/core-project-message        | 10.4.4        | 10.4.5        |
| drupal/core-recommended            | 10.4.4        | 10.4.5        |
| drupal/csp                         | 1.33.0        | 1.40.0        |
| drupal/eca                         | 2.1.5         | 2.1.6         |
| …
```
=> convivial-demo-41386: Site Updates and Custom Metatags: Blanks
